function f = parameter_interactor(constants, mode)
    % Create the main figure
    
    % create limits for parameters
     limits = struct(...
        'battery_energy', [0, 100000000], ...             % Wh
        'battery_voltage', [0, 100000000], ...            % V
        'battery_capacity', [0, 1000000], ...           % Ah
        'battery_current', [0, 1000000], ...            % A
        'battery_mass', [0, 1000000], ...               % kg
        'battery_volume', [0, 1000000], ...             % liters
        'battery_power', [0, 1000000], ...
        'battery_efficiency', [0, 1000000], ...
        'cell_energy', [0, 10000000], ...                % Wh
        'cell_voltage', [0, 100000000], ...               % V
        'cell_capacity', [0, 10000000], ...              % Ah
        'cell_current', [0, 10000000], ...               % A
        'cell_mass', [0, 10000000], ...                  % kg
        'cell_volume', [0, 10000000], ...                % liters
        'serial_conections', [0, 100000000], ...          % Number of serial connections
        'parallel_connections', [0, 10000000], ...       % Number of parallel connections
        'motor_peak_power', [0, 1000000000], ...           % kW
        'motor_peak_torque', [0, 10000000], ...  
        'motor_mass', [0, 10000000], ...               % kg
        'motor_efficency', [0, 1000000], ...            % Efficiency
        'gearbox_ratio', [0, 10000000], ...              % Ratio
        'gearbox_max_torque', [0, 1000000], ...         % Nm
        'gearbox_mass', [0, 1000000], ...             % kg
        'gearbox_efficency', [0, 1000000], ...          % Efficiency
        'inverter_efficency', [0, 1000000], ...         % Efficiency
        'vehicle_max_speed', [0, 10000000], ...          % km/h
        'vehicle_acc_time', [0, 10000000], ...           % Seconds (0-100 km/h)
        'vehicle_consumption', [0, 10000000], ...        % kWh/100 km
        'vehicle_range', [0, 10000000], ...              % km
        'vehicle_efficency', [0, 100000000], ...          % Efficiency
        'vehicle_mass', [0, 10000000]);                 % 
    
    [f, fields] = create_parameter_interaction_panel();

    % Global variable to store battery parameters
        global globalParameters 
        globalParameters = struct(...
        'battery_energy', 0, ...
        'battery_voltage', 0, ...
        'battery_capacity', 0, ...
        'battery_current', 0, ...
        'battery_power',0, ...
        'battery_efficiency',0, ...
        'battery_mass', 0, ...
        'battery_volume', 0, ...
        'cell_energy', 0, ...
        'cell_voltage', 0, ...
        'cell_capacity', 0, ...
        'cell_current', 0, ...
        'cell_mass', 0, ...
        'cell_volume', 0, ...
        'serial_conections', 0, ...
        'parallel_connections', 0, ...
        'motor_peak_power', 0, ...
        'motor_peak_torque', 0,...
        'motor_mass', 0, ...
        'motor_efficiency', 0, ...
        'gearbox_ratio', 0, ...
        'gearbox_max_torque', 0, ...
        'gearbox_mass', 0, ...
        'gearbox_efficiency', 0, ...
        'inverter_efficiency', 0);
    
    % create parameters list 
      parameters = struct(...
        'battery_energy', 0, ...
        'battery_voltage', 0, ...
        'battery_capacity', 0, ...
        'battery_current', 0, ...
        'battery_mass', 0, ...
        'battery_volume', 0, ...
        'battery_power',0, ...
        'battery_efficiency',0, ...
        'cell_energy', 0, ...
        'cell_voltage', 0, ...
        'cell_capacity', 0, ...
        'cell_current', 0, ...
        'cell_mass', 0, ...
        'cell_volume', 0, ...
        'serial_conections', 0, ...
        'parallel_connections', 0, ...
        'motor_peak_power', 0, ...
        'motor_peak_torque', 0,...
        'motor_mass', 0, ...
        'motor_efficiency', 0, ...
        'gearbox_ratio', 0, ...
        'gearbox_max_torque', 0, ...
        'gearbox_mass', 0, ...
        'gearbox_efficiency', 0, ...
        'inverter_efficiency', 0);              
    
    % Define symbolic variables for battery equations  
        syms battery_energy battery_voltage battery_capacity battery_current battery_mass battery_volume battery_efficiency ...
        cell_energy cell_voltage cell_capacity cell_current cell_mass cell_volume ...
        serial_conections parallel_connections ...
        motor_peak_power  motor_mass motor_efficiency ...
        gearbox_ratio gearbox_max_torque gearbox_mass gearbox_efficiency ...
        inverter_efficiency motor_corner_speed stages battery_power motor_peak_torque const_mass ...
        vehicle_consumption vehicle_range vehicle_efficiency vehicle_mass battery_current motor_specific_weight
    
    switch mode
        case 'default'
         % Define parameters that should not be intialized nor edited. Their values remain untouched   
         nonedit = struct('cell_energy', 0, 'cell_voltage', 0, 'cell_capacity', 0, 'cell_current', 0,  'cell_mass', 0, 'inverter_efficiency', 0, 'battery_efficiency', 0, 'motor_efficiency', 0, 'gearbox_efficiency', 0);%, 'serial_conections', 0, 'parallel_connections', 0);
         
         % Complete priority list for all battery parameters
            priorityList = {...
            'battery_capacity', ...
            'battery_voltage', ...
            'battery_current', ...
            'battery_efficiency', ...
            'parallel_connections', ...
            'serial_conections', ... 
            'battery_energy', ...
            'battery_power', ...
            'cell_energy', ...
            'cell_voltage', ...
            'cell_capacity', ...
            'cell_current', ...
            'inverter_efficiency', ...
            'motor_efficiency', ...
            'gearbox_efficiency', ...
            'motor_peak_power', ...
            'motor_peak_torque', ...
            'gearbox_ratio', ...
            'gearbox_max_torque', ...
            'battery_mass', ...
            'battery_volume', ...
            'cell_mass', ...
            'cell_volume', ...
            'motor_mass', ...
            'gearbox_mass', ...
            'vehicle_mass', ...
            'vehicle_max_speed', ...
            'vehicle_acc_time', ...
            'vehicle_consumption', ...
            'vehicle_range', ...
            'vehicle_efficiency' ...
            };

        case 'design_battery' %meant for chnages outisde the battery % chnage its name it didnt do anythign to the cell! the cell could techincall be unchangable 

            nonedit = struct(  'cell_mass', 0, 'cell_capacity',0,  'cell_voltage',0,  'cell_energy', 0, 'cell_current',0,  'battery_efficiency', 0, 'inverter_efficiency', 0, 'motor_efficiency', 0, 'gearbox_efficency', 0);%, 'serial_conections', 0, 'parallel_connections', 0);
            
            priorityList = {...
            'inverter_efficiency', ...
            'motor_efficiency', ...
            'gearbox_efficiency', ...
            'battery_efficiency', ...
            'motor_peak_power', ...
            'motor_peak_torque', ...
            'motor_mass', ...
            'gearbox_ratio', ...
            'gearbox_max_torque', ...
            'gearbox_mass', ...
            'vehicle_mass', ...
            'cell_voltage', ...
            'cell_capacity', ...
            'cell_energy', ...
            'cell_current', ...
            'cell_mass', ...
            'cell_volume', ...
            'serial_conections', ...
            'parallel_connections', ...
            'battery_capacity', ...
            'battery_current', ...
            'battery_voltage', ...
            'battery_energy', ...
            'battery_power', ...
            'battery_mass', ...
            'battery_volume', ...
            'vehicle_max_speed', ...
            'vehicle_acc_time', ...
            'vehicle_consumption', ...
            'vehicle_range', ...
            'vehicle_efficiency' ...
            }; 

        case 'design_cell' %more like electrocal

            nonedit = struct('battery_efficiency', 0, 'inverter_efficiency', 0, 'motor_efficiency', 0, 'gearbox_efficency', 0);%, 'serial_conections', 0, 'parallel_connections', 0);
            
            priorityList = {...
            'inverter_efficiency', ...
            'motor_efficiency', ...
            'gearbox_efficiency', ...
            'battery_efficiency', ...
            'motor_peak_power', ...
            'motor_peak_torque', ...
            'motor_mass', ...
            'gearbox_ratio', ...
            'gearbox_max_torque', ...
            'gearbox_mass', ...
            'vehicle_mass', ...
            'battery_energy', ...
            'battery_power', ...
            'battery_voltage', ...
            'battery_capacity', ...
            'battery_current', ...
            'battery_mass', ...
            'battery_volume', ...
            'serial_conections', ...
            'parallel_connections', ...
            'cell_voltage', ...
            'cell_capacity', ...
            'cell_energy', ...
            'cell_current', ...
            'cell_mass', ...
            'cell_volume', ...
            'vehicle_max_speed', ...
            'vehicle_acc_time', ...
            'vehicle_consumption', ...
            'vehicle_range', ...
            'vehicle_efficiency' ...
            }; 
        
    end

    % Define equations for cell and battery level
    equations = { ...
        battery_voltage == cell_voltage * serial_conections, ...                         % Battery voltage
        battery_capacity == cell_capacity * parallel_connections, ...                    % Battery capacity
        battery_current == cell_current * parallel_connections, ...                      % Battery current
        battery_energy == battery_voltage * battery_capacity, ...
        battery_power == battery_voltage * battery_current, ...
        battery_mass == cell_mass * serial_conections * parallel_connections * 1.2, ...        % Battery mass
        battery_volume == cell_volume * serial_conections * parallel_connections * 1.1, ...    % Battery volume
        motor_peak_power == battery_power * inverter_efficiency * battery_efficiency * 0.85, ...  % Motor peak power (alternative equation) 
        motor_peak_power == (motor_peak_torque * motor_corner_speed) / 9.5488, ...
        motor_mass == motor_specific_weight * motor_peak_torque, ...                             % Motor weigh 
        gearbox_max_torque == motor_peak_torque*motor_efficiency, ...
        gearbox_mass == 0.199*((gearbox_ratio*gearbox_max_torque)^0.669*stages^0.334), ...                      % Gearbox weight
        };
    
    % Output equations (calculate at the very end)
        outputEquations = { ...
            vehicle_efficiency == motor_efficiency * gearbox_efficiency * inverter_efficiency * battery_efficiency, ...
            vehicle_mass == const_mass + motor_mass + battery_mass + gearbox_mass, ...                  
        };
    
    
    % Add listeners for all parameters with limit enforcement
    addlistener(fields.battery_energy, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.battery_energy(1), limits.battery_energy(2), 'battery_energy', fields, parameters, equations, priorityList, nonedit, outputEquations, constants, limits));
    addlistener(fields.battery_voltage, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.battery_voltage(1), limits.battery_voltage(2), 'battery_voltage', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.battery_capacity, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.battery_capacity(1), limits.battery_capacity(2), 'battery_capacity', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.battery_current, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.battery_current(1), limits.battery_current(2), 'battery_current', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.battery_mass, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.battery_mass(1), limits.battery_mass(2), 'battery_mass', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.battery_volume, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.battery_volume(1), limits.battery_volume(2), 'battery_volume', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.cell_energy, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.cell_energy(1), limits.cell_energy(2), 'cell_energy', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.cell_voltage, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.cell_voltage(1), limits.cell_voltage(2), 'cell_voltage', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.cell_capacity, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.cell_capacity(1), limits.cell_capacity(2), 'cell_capacity', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.cell_current, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.cell_current(1), limits.cell_current(2), 'cell_current', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.cell_mass, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.cell_mass(1), limits.cell_mass(2), 'cell_mass', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.cell_volume, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.cell_volume(1), limits.cell_volume(2), 'cell_volume', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.serial_conections, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.serial_conections(1), limits.serial_conections(2), 'serial_conections', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.parallel_connections, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.parallel_connections(1), limits.parallel_connections(2), 'parallel_connections', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits ));
    addlistener(fields.motor_peak_power, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.motor_peak_power(1), limits.motor_peak_power(2), 'motor_peak_power', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.motor_peak_torque, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.motor_peak_torque(1), limits.motor_peak_torque(2), 'motor_peak_torque', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.motor_mass, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.motor_mass(1), limits.motor_mass(2), 'motor_mass', fields, parameters, equations, priorityList, nonedit,  outputEquations , constants, limits));
    addlistener(fields.motor_efficiency, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.motor_efficency(1), limits.motor_efficency(2), 'motor_efficiency', fields, parameters, equations, priorityList, nonedit,outputEquations , constants, limits));
    addlistener(fields.gearbox_ratio, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.gearbox_ratio(1), limits.gearbox_ratio(2), 'gearbox_ratio', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.gearbox_max_torque, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.gearbox_max_torque(1), limits.gearbox_max_torque(2), 'gearbox_max_torque', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.gearbox_mass, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.gearbox_mass(1), limits.gearbox_mass(2), 'gearbox_mass', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.gearbox_efficiency, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.gearbox_efficency(1), limits.gearbox_efficency(2), 'gearbox_efficiency', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.inverter_efficiency, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.inverter_efficency(1), limits.inverter_efficency(2), 'inverter_efficiency', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.battery_chemistry, 'ValueChanged', @(src, event) updateBatteryParameters(src, fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    addlistener(fields.motor_type, 'ValueChanged', @(src, event) updateMotorParameters(src, fields, parameters, equations, priorityList, nonedit, outputEquations, constants, limits));
    addlistener(fields.inverter_type, 'ValueChanged', @(src, event) updateInverterParameters(src, fields, parameters, equations, priorityList, nonedit, outputEquations, constants, limits));
    addlistener(fields.battery_efficiency, 'ValueChanged', @(src, event) function_handle_user_input(src, limits.battery_efficiency(1), limits.battery_efficiency(2), 'battery_efficiency', fields, parameters, equations, priorityList, nonedit, outputEquations , constants, limits));
    
end


function updateInverterParameters(src, fields, parameters, equations, priorityList, nonedit, outputEquations, constants, limits)
    % Update Inverter Parameters
    % This function updates the inverter efficiency based on the selected inverter type (IGBT or MOSFET).
    % It modifies global parameters, updates the UI fields, and triggers a recalculation of outputs.

    % Get the selected inverter type from the dropdown
    inverter_type = src.Value; % Options: 'IGBT' or 'MOSFET'

    % Define global parameters
    global globalParameters;

    % Update globalParameters based on the selected inverter type
    switch inverter_type
        case 'MOSFET'
            globalParameters.inverter_efficiency = 0.97; % MOSFET efficiency
        case 'IGBT'
            globalParameters.inverter_efficiency = 0.93; % IGBT efficiency
        otherwise
            % Handle invalid selection
            error('Invalid inverter type. Choose from IGBT or MOSFET.');
    end

    % Update the UI fields with the new inverter efficiency value
    fields.inverter_efficiency.Value = globalParameters.inverter_efficiency;

    % Trigger recalculation and update all relevant outputs
    init_recalculate_update('inverter_efficiency', fields, parameters, equations, priorityList, nonedit, outputEquations, constants, limits);
end


function updateMotorParameters(src, fields, parameters, equations, priorityList, nonedit, outputEquations, constants, limits)
    % Update Motor Parameters
    % This function updates motor efficiency and specific weight based on the selected motor type (PSM, ASM, or SRM).
    % It modifies global parameters, updates UI fields, and triggers recalculation of outputs.

    % Get the selected motor type from the dropdown
    motor_type = src.Value; % Options: 'PSM', 'ASM', or another motor type

    % Update constants based on the selected motor type
    switch motor_type
        case 'PSM'
            motor_efficiency = 0.95; % Permanent Magnet Synchronous Motor
            constants.motor_specific_weight = 0.25; 
            constants.motor_corner_speed = 3000; 
        case 'ASM'
            motor_efficiency = 0.90; % Asynchronous Motor
            constants.motor_specific_weight = 0.35; 
            constants.motor_corner_speed = 2000; 
        otherwise
            % Handle invalid motor type selection
            error('Invalid motor type. Choose from PSM or ASM.');
    end

    % Update constants in the base workspace
    assignin('base', 'constants', constants);

    % Define global parameters
    global globalParameters;
    globalParameters.motor_efficiency = motor_efficiency; % Update motor efficiency

    % Update the UI fields with new motor parameter values
    fields.motor_efficiency.Value = motor_efficiency;

    % Trigger recalculation and update all relevant outputs
    init_recalculate_update('motor_efficiency', fields, parameters, equations, priorityList, nonedit, outputEquations, constants, limits);
end


function updateBatteryParameters(batteryChemistryField, fieldsall, parameters, equations, priorityList, nonedit, outputEquations, constants, limits)
    % Update Battery Parameters
    % This function updates battery parameters based on the selected battery chemistry.
    % It updates global parameters, the UI fields, and triggers recalculation of outputs.

    % Get the selected battery chemistry from the dropdown
    selectedChemistry = batteryChemistryField.Value;

    % Define default parameter ranges for each chemistry type
    switch selectedChemistry
        case 'Cylindrical NMC811 5Ah'
            cellParams = struct( ...
                'cell_energy', [17.456, 17.456], ...      % Wh
                'cell_voltage', [3.6, 3.6], ...          % V
                'cell_capacity', [4.8490, 4.8490], ...   % Ah
                'cell_current', [14.5471, 14.5471], ...  % A
                'cell_mass', [0.0685, 0.0685], ...       % kg
                'cell_volume', [2.4245e-5, 2.4245e-5]);  % m³ (calculated from cylinder formula)

        case 'Prismatic NMC811 168Ah'
            cellParams = struct( ...
                'cell_energy', [605, 605], ...        % Wh
                'cell_voltage', [3.6, 3.6], ...       % V
                'cell_capacity', [168.1, 168.1], ...  % Ah
                'cell_current', [504.1667, 504.1667], ... % A
                'cell_mass', [2.5, 2.5], ...          % kg
                'cell_volume', [0.001, 0.001]);       % m³ (calculated as 0.04 * 0.2 * 0.125)
        
        case 'Cylindrical NMC721 27Ah'
            cellParams = struct( ...
                'cell_energy', [95.73, 95.73], ...      % Wh
                'cell_voltage', [3.6, 3.6], ...        % V
                'cell_capacity', [26.59, 26.59], ...   % Ah
                'cell_current', [79.77, 79.77], ...    % A
                'cell_mass', [0.3754, 0.3754], ...     % kg
                'cell_volume', [0.00004234, 0.00004234]);  % m³ (calculated from cylinder formula)
        
        case 'Pouch NMC811 109Ah'
            cellParams = struct( ...
                'cell_energy', [392.44, 392.44], ...   % Wh
                'cell_voltage', [3.6, 3.6], ...       % V
                'cell_capacity', [109, 109], ...      % Ah
                'cell_current', [327, 327], ...       % A
                'cell_mass', [1.45, 1.45], ...        % kg
                'cell_volume', [0.006825, 0.006825]); % m³ (calculated as 0.013 * 0.3 * 0.1750)

        case 'Prismatic LFP 249Ah'
            cellParams = struct( ...
                'cell_energy', [798, 798], ...         % Wh
                'cell_voltage', [3.2, 3.2], ...       % V
                'cell_capacity', [249.38, 249.38], ...% Ah
                'cell_current', [748.13, 748.13], ... % A
                'cell_mass', [4.9875, 4.9875], ...    % kg
                'cell_volume', [0.021, 0.021]);       % m³ (calculated as 0.06 * 0.2 * 0.1750)
        
        case 'Prismatic NMC811 529Ah'
            cellParams = struct( ...
                'cell_energy', [1905.8, 1905.8], ...   % Wh
                'cell_voltage', [3.6, 3.6], ...       % V
                'cell_capacity', [529.38, 529.38], ...% Ah
                'cell_current', [1588.1, 1588.1], ... % A
                'cell_mass', [7.88, 7.88], ...        % kg
                'cell_volume', [0.0315, 0.0315]);     % m³ (calculated as 0.04 * 0.45 * 0.175) 
        otherwise
            error('Unsupported battery chemistry. Choose from Lithium-Ion, Nickel-Metal Hydride, or LFP.');
    end

    % Update global parameters with averaged cell values
    global globalParameters;
    globalParameters.cell_energy = mean(cellParams.cell_energy);
    globalParameters.cell_voltage = mean(cellParams.cell_voltage);
    globalParameters.cell_capacity = mean(cellParams.cell_capacity);
    globalParameters.cell_current = mean(cellParams.cell_current);
    globalParameters.cell_mass = mean(cellParams.cell_mass);
    globalParameters.cell_volume = mean(cellParams.cell_volume);

    % Update the UI fields with the updated cell parameter values
    fieldsall.cell_energy.Value = mean(cellParams.cell_energy);
    fieldsall.cell_voltage.Value = mean(cellParams.cell_voltage);
    fieldsall.cell_capacity.Value = mean(cellParams.cell_capacity);
    fieldsall.cell_current.Value = mean(cellParams.cell_current);
    fieldsall.cell_mass.Value = mean(cellParams.cell_mass);
    fieldsall.cell_volume.Value = mean(cellParams.cell_volume);

    % Trigger recalculation and update all relevant outputs
    init_recalculate_update('cell_mass', fieldsall, parameters, equations, priorityList, nonedit, outputEquations, constants, limits);
end


